# Generated by Django 5.1.6 on 2025-03-04 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('keyword', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=True)),
                ('max_depth', models.IntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawlers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(max_length=50)),
                ('relevance_score', models.FloatField()),
                ('keywords', models.CharField(max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='scraper.crawler')),
            ],
            options={
                'indexes': [models.Index(fields=['keywords'], name='scraper_lin_keyword_dc1d3c_idx'), models.Index(fields=['type'], name='scraper_lin_type_4645a8_idx'), models.Index(fields=['relevance_score'], name='scraper_lin_relevan_b4d94b_idx')],
                'unique_together': {('url', 'crawler')},
            },
        ),
    ]
